# Note  : *** the batch_size should be equal to the gpus number at the test phase!!! ***
data_cfg:
  dataset_name: CASIA-B
  dataset_root: /home/akash/Use/DL_Project/DL_Project-main/CASIA-B-pkl
  dataset_partition: ./datasets/CASIA-B/CASIA-B.json # for train and test
  num_workers: 1
  remove_no_gallery: false
  test_dataset_name: CASIA-B

evaluator_cfg:
  enable_float16: false 
  restore_ckpt_strict: true
  restore_hint: 80000
  save_name: autogaitformer
  sampler:
    batch_size: 1 ## Keep this eqaul to the gpus number
    sample_type: all_ordered
    type: InferenceSampler

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2 #margin for triplet loss
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: false
    log_prefix: softmax

model_cfg:
  model: AutoGaitFormer
  channels: [32, 64, 128]
  class_num: 74
  block_height : [4, 8, 16]
  patch_size : [4, [8, 4], [16, 8, 4]]

optimizer_cfg:
  lr: 1.0e-4
  solver: Adam
  weight_decay: 5.0e-4

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 70000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  with_test: false
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: autogaitformer
  sync_BN: true
  total_iter: 80000
  sampler:
    batch_shuffle: true
    batch_size:
      - 3 # TripletSampler, batch_size[0] indicates Number of Identity
      - 2 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30 # fixed frames number for training
    frames_skip_num: 0 # min frames number for unfixed traing
    sample_type: fixed_ordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    type: TripletSampler
